### ISSUE TITLE
Feature request: add Methfessel-Paxton smearing to CP2K

### ISSUE THREAD

**Issue by GengSS** [cp2k/cp2k#2395] opened 2022-11-15 06:10 UTC
Dear CP2K developers,
I wonder is that possible to add the Methfessel-Paxton smearing to CP2K as an alternative for the Fermi-Dirac method?
As best as I know, in the Methfessel-Paxton method, the integration (electron free energy) is less sensitive to the electron temperature. This is very important in metallic system. However, in the Fermi-Dirac method, the electron entropy is enormous when using FERMI_DIRAC method with a few hundred Kelvins for electron temperature.

Best Wishes,
Geng

**Comment by GengSS** [comment] 2022-11-15 06:12
one test can be found on the page 5 of the quantum ATK documents here:
https://docslib.org/doc/4899473/occupation-methods-quantumatk-s-2021-06-documentation

**Comment by oschuett** [comment] 2022-12-21 13:33
Duplicate of #1359.

**Closed as completed by oschuett** 2022-12-21 13:33 UTC
