### ISSUE TITLE
fails to build with GCC 10: Element of assumed-shape or pointer array as actual argument at (1) cannot correspond to actual argument at (2)

### ISSUE THREAD

**Issue by yurivict** [cp2k/cp2k#1167] opened 2020-11-15 22:21 UTC
OS: FreeBSD 12.2
Rev. 2e995eec7fd208c8a72d9544807bd8b8ba8cd1cc

**Comment by dev-zero** [comment] 2020-12-04 08:10
this is a duplicate of #969 and has been fixed in the current master and will be fixed in v8.1

**Closed as completed by dev-zero** 2020-12-04 08:10 UTC
Labels: duplicate
