### ISSUE TITLE
cp2k@8.2 test failed on centos8_aarch64

### ISSUE THREAD

**Issue by alikaba** [cp2k/cp2k#1649] opened 2021-09-23 07:52 UTC
Hello,I meet a problem:cp2k@master test failed on centos8_aarch64 .
**Steps to reproduce the issue**
command:make -j10 ARCH=linux-centos8-aarch64-gcc VERSION=popt test
errors :
 *******************************************************************************
 *   ___                                                                       *
 *  /   \                                                                      *
 * [ABORT]                                                                     *
 *  \___/                             CPASSERT failed                          *
 *    |                                                                        *
 *  O/|                                                                        *
 * /| |                                                                        *
 * / \                                            fm/cp_cfm_basic_linalg.F:891 *
 *******************************************************************************

 *******************************************************************************
 *   ___                                                                       *
 *  /   \  
 ===== Routine Calling Stack ===== 

           10 cp_cfm_cholesky_decompose
                                                                    *
 *            9 cholesky_decomp_Q
 [ABORT]                                                                     *
 *  \___/              8 RPA_postprocessing_kp
            7 rpa_num_int_RPA_matrix_operations
                           CPASSERT failed                          *
 *    |                                                  6 rpa_num_int
            5 rpa_ri_compute_en
            4 mp2_gpw_main
            3 mp2_main
            2 qs_energies
            1 CP2K
                                  *
 *  O/|                                                                        *
 * /| |                                                                        *
 * / \                                            fm/cp_cfm_basic_linalg.F:891 *
 *******************************************************************************

 ===== Routine Calling Stack ===== 

           10 cp_cfm_cholesky_decompose
            9 cholesky_decomp_Q
            8 RPA_postprocessing_kp
            7 rpa_num_int_RPA_matrix_operations
            6 rpa_num_int
            5 rpa_ri_compute_en
            4 mp2_gpw_main
            3 mp2_main
            2 qs_energies
            1 CP2K
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[centos8:2384204] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[centos8:2384204] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
EXIT CODE:  1  MEANING:  RUNTIME FAIL

could you take a look ?

**Comment by oschuett** [comment] 2021-11-08 12:08
Sorry for the late reply.
Unfortunately, this is not enough information to start debugging.
Generally, ARM support is an area of focus for us. So, maybe your problem got already resolved?
Since this question is already pretty old I'm closing it for now.
Feel free to reopen if the issue is still present.

**Closed as completed by oschuett** 2021-11-08 12:08 UTC
