### ISSUE TITLE
dtrsl references undefined variable b(1)

### ISSUE THREAD

**Issue by vzecca** [cp2k/cp2k#1306] opened 2021-01-14 14:30 UTC
Running test case QS/regtest-gpw-4/H2-geo-5.inp the variable b(1) is referenced undefined
in file cp_lbfgs.F line 3779:

b(1) = b(1)/t(1, 1)

This happens on fifth time b(1) is referenced.

**Comment by oschuett** [comment] 2021-02-02 11:40
Duplicate of #1305.

**Closed as completed by oschuett** 2021-02-02 11:40 UTC
Labels: duplicate
