### ISSUE TITLE
CP2K relies on DBCSR internals

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1260] opened 2020-12-29 09:29 UTC
CP2K directly calls into DBCSR here:

https://github.com/cp2k/cp2k/blob/502e97e1991a6fd4d2c0ba27ea722fa2446a12a5/src/start/cp2k_runs.F#L50

This will not be available anymore once DBCSR is built separately.

**Comment by alazzaro** [comment] 2020-12-29 11:58
This is a leftover, which requires to have that function in CP2K directly (mostly related to the PW_CUDA). See #814

**Comment by oschuett** [comment] 2021-02-02 12:21
This is a duplicate of #814.

**Closed as completed by oschuett** 2021-02-02 12:21 UTC
Labels: duplicate
