### ISSUE TITLE
Argument aliasing of matrix_x in dm_ls_scf_methods provokes assignment to INTENT(IN) dummy matrix_a

### ISSUE THREAD

**Issue by vzecca** [cp2k/cp2k#1037] opened 2020-08-17 07:10 UTC
Running test case xTB/regtest-4/H2O-xtb-tc2-1.inp 
(and QS/regtest-dm-ls-scf-3/H2O-dftb-tc2-1.inp and more)
an argument aliasing of matrix_x in dm_ls_scf_methods.F:1074

CALL dbcsr_multiply("N", "N", 1.0_dp, matrix_x, matrix_s_sqrt_inv, &
                          0.0_dp, matrix_x, filter_eps=threshold)

provokes later in dbcsr_mm.F:932
matrix_c = dbcsr_type()
an assignment to matrix_c that affects INTENT(IN) dummy argument matrix_a

**Comment by juerghutter** [comment] 2020-08-18 11:04
Should be fixed by commit 8db5d09a5b4b2ae677ad6776ea8e5b04acd74d55

**Comment by vzecca** [comment] 2020-08-20 08:03
Another alias at rpa_axk.F lines 462 and 463

CALL dbcsr_multiply("T", "N", 1.0_dp, mat_2d(1,
)%matrix,dbcsr_Gamma_munu_P(aux)%matrix, &
                             0.0_dp, dbcsr_Gamma_munu_P(aux)%matrix,
filter_eps=eps_filter)

produces the same issue, aliasing dbcsr_Gamma_munu_P(aux)%matrix

**Comment by vzecca** [comment] 2020-08-20 13:19
Another bad alias at dm_ls_scf.F line 909

         CALL dbcsr_multiply("N", "N", 1.0_dp, matrix_k,
ls_scf_env%matrix_s_sqrt_inv, &
                             0.0_dp, matrix_k, filter_eps=ls_scf_env%eps_filter)

on matrix_k

**Comment by vzecca** [comment] 2020-08-20 13:21
And at dm_ls_scf_methods.F line 1215

     CALL dbcsr_multiply("N", "N", 1.0_dp, matrix_s_sqrt_inv, matrix_p, &
                          0.0_dp, matrix_p, filter_eps=threshold)

**Comment by vzecca** [comment] 2020-08-20 13:24
And xas_tdp_utils.F:536

        CALL dbcsr_multiply('N', 'N', 1.0_dp, tmp_mat, donor_state%matrix_aux, &
                             0.0_dp, tmp_mat,
filter_eps=xas_tdp_control%eps_filter)

on tmp_mat

**Comment by vzecca** [comment] 2020-08-20 13:26
And iterate_matrix.F:881

           CALL dbcsr_multiply("N", "N", 1.0_dp, tmp2, tmp3, 0.0_dp, tmp2, &
                                filter_eps=threshold, flop=flops)

on tmp2

**Comment by abussy** [comment] 2020-08-20 15:23
This PR #1048 should solve the issue in the XAS_TDP code. In general, this seems to be quite frequent in CP2K. I can try and fix it everywhere, but it might take some time. Should I take care of it @juerghutter ?

**Comment by oschuett** [comment] 2020-08-20 19:15
Maybe this is not a bug but a feature? AFAIK, `dbcsr_multiply` creates copies of its input matrices before writing to the result matrix. So, aliasing shouldn't lead to any wrong results.

Nevertheless, if we really want to ban this pattern then we should add a check to DBCSR.

**Comment by abussy** [comment] 2020-08-20 19:23
I tend to agree. I personally quite like being able to overwrite the output matrix, this allows me carry around (and think about) less temporary matrices.

**Comment by vzecca** [comment] 2020-08-21 06:07
This aliasing is writing onto INTENT(IN) dummy arguments.

You will never know when a compiler upgrade will discard such modifications
thus losing them.

**Comment by abussy** [comment] 2020-08-24 10:54
I believe that #1048 now fixes all occurrences of bas aliasing in dbcsr multiplication. I do think that adding an additional test in `dbcsr_multiply` might be a good idea though, just to prevent that from happening again.

**Comment by hfp** [comment] 2020-08-24 14:18
> AFAIK, dbcsr_multiply creates copies of its input matrices before writing to the result matrix. So, aliasing shouldn't lead to any wrong results.

I have not looked at the referred code (and probably I misunderstand the context), but removing aliases upfront (call side) would this allow to remove such copies in DBCSR? It sounds a bit awkward creating copies of input matrices.

**Comment by abussy** [comment] 2020-08-24 15:04
In most cases, you have something like the situation below, where `P <- SPS`, with the two intermediate steps being `P <- SP` followed by `P <- PS`, so using an explicit temporary matrix is rather natural and does not require copies of the input matrices.
https://github.com/cp2k/cp2k/blob/b1360cdddb25194b956e246e9b787b17440c1a54/src/dm_ls_scf.F#L913-L916 

It does however feel awkward in the following case, where `Rmat` is elevated to a certain power within a loop. Here I do not see how to escape copying the input matrix.
https://github.com/cp2k/cp2k/blob/b1360cdddb25194b956e246e9b787b17440c1a54/src/iterate_matrix.F#L1987-L1997

I do not know whether DBCSR always copies input matrices though. If it is the case, then fixing the above code leads to copying input matrices twice, which is of course not great.

**Comment by hfp** [comment] 2020-08-24 15:33
@abussy thank you for the insight!  ( I believe this can be turned into an issue if DBCSR creates deep copies for inputs in all cases. )

**Comment by abussy** [comment] 2020-10-26 08:53
Refresher: the code is now free of those argument aliasings. The question remains as to whether DBCSR should explicitely check for that though.

**Closed as completed** 2022-04-25 12:38 UTC
