### ISSUE TITLE
New GCC versions break toolchain builds

### ISSUE THREAD

**Issue by dogunter** [cp2k/cp2k#352] opened 2019-05-10 22:54 UTC
I'm using GCC 7.40 with CUDA 10.0 to build the main branch on a system. Everything proceeds smoothly with the toolchain and then when I go to build cp2k using the generate setup file and the generated arch file, it breaks with the following error:

```
gfortran -c -march=native -fno-omit-frame-pointer -g  -O1  -fopenmp  -I'/usr/projects/icapt/dog/benchmarking/cp2k/tools/toolchain/install/fftw-3.3.8/include' -I'/usr/projects/icapt/dog/benchmarking/cp2k/tools/toolchain/install/libint-1.1.6/include' -I'/usr/projects/icapt/dog/benchmarking/cp2k/tools/toolchain/install/libxc-4.3.4/include' -I'/usr/projects/icapt/dog/benchmarking/cp2k/tools/toolchain/install/libxsmm-1.10.0/include' -I'/usr/projects/icapt/dog/benchmarking/cp2k/tools/toolchain/install/gsl-2.5/include' -I/usr/projects/icapt/dog/benchmarking/cp2k/tools/toolchain/install/spglib-1.12.2/include -I/usr/projects/icapt/dog/benchmarking/cp2k/tools/toolchain/install/hdf5-1.10.4/include  -I'/usr/projects/icapt/dog/benchmarking/cp2k/tools/toolchain/install/json_fortran-7.0.0/include' -ffree-form -std=f2008 -fimplicit-none -fsanitize=leak -fcheck=all -ffpe-trap=invalid,zero,overflow -finit-derived -finit-real=snan -finit-integer=-42 -Werror=realloc-lhs-all -finline-matmul-limit=0 -Werror=aliasing -Werror=ampersand -Werror=c-binding-type -Werror=intrinsic-shadow -Werror=intrinsics-std -Werror=line-truncation -Werror=tabs -Werror=target-lifetime -Werror=underflow -Werror=unused-but-set-variable -Werror=unused-variable -Werror=unused-dummy-argument -Werror=conversion -Werror=zerotrip -Werror=uninitialized -Wno-maybe-uninitialized -Wuse-without-only  -D__ACC -D__DBCSR_ACC -D__PW_CUDA -D__CUDA_PROFILING -D__LIBXSMM  -D__FFTW3  -D__LIBINT -D__LIBINT_MAX_AM=6 -D__LIBDERIV_MAX_AM1=5 -D__LIBXC  -D__SPGLIB   -D__JSON -D__HAS_IEEE_EXCEPTIONS -D__CHECK_DIAG  -D__COMPILE_ARCH="\"kodiak-gcc-cuda\"" -D__COMPILE_DATE="\"Fri May 10 16:46:52 MDT 2019\"" -D__COMPILE_HOST="\"ko-fe1.lanl.gov\"" -D__COMPILE_REVISION="\"git:158053f\"" -D__DATA_DIR="\"/turquoise/usr/projects/icapt/dog/benchmarking/cp2k/data\"" -D__SHORT_FILE__="\"xc/xc_rho_cflags_types.F\"" -I'/turquoise/usr/projects/icapt/dog/benchmarking/cp2k/src/xc/' -I'/turquoise/usr/projects/icapt/dog/benchmarking/cp2k/obj/kodiak-gcc-cuda/sdbg/exts/dbcsr' xc_rho_cflags_types.F90 
/turquoise/usr/projects/icapt/dog/benchmarking/cp2k/src/xc/xc_rho_cflags_types.F:61:0:

    SUBROUTINE xc_rho_cflags_setall(cflags, value)
 
Error: ‘xc_rho_cflags_type.0’ is used uninitialized in this function [-Werror=uninitialized]
f951: some warnings being treated as errors
make[3]: *** [xc_rho_cflags_types.o] Error 1
make[2]: *** [all] Error 2
make[1]: *** [sdbg] Error 2
make: *** [all] Error 2
```

The problem is that the `-finit-derived` flag combined with the `-Werror-uninitialized` flag are causing subroutines to be flagged if uninitialized variables are passed into them, even though the variables are marked as `INTENT(IN)`.

The work-around for now is to add the flag `-finit-local-zero`, which "instructs the compiler to initialize local INTEGER, REAL, and COMPLEX variables to zero, LOGICAL variables to false, and CHARACTER variables to a string of null bytes."

Can this be added as part of the routine build process?

**Comment by dev-zero** [comment] 2019-12-03 09:07
Thank you for the report and sorry for not responding earlier. Unfortunately I can't reproduce this error, neither with a vanilla gcc-7.4.0, nor with gcc-7.4.1 from openSUSE.
Setting `-finit-local-zero` is unfortunately the wrong way here since this completely disables the purpose of the `-Werror=uninitialized`. So, if at all we should remove all `-finit-*` instead, which would likely make it worse in your case.
My guess is that your compiler configuration has some extra configuration makes it complain about something completely legal, hence this is rather a compiler bug.

Nevertheless, it would still be interesting to see the output of `gfortran -dumpspecs` and to know whether this was with a vanilla compiler or a distro provided one. Can you still reproduce this and could you provide those details?

**Comment by oschuett** [comment] 2020-01-13 10:04
I'm closing this as we can't reproduce it and the toolchain has moved to GCC 9.2 in the meantime.

**Closed as completed by oschuett** 2020-01-13 10:04 UTC
Labels: needinfo
