### ISSUE TITLE
Performance regression in cp_fm_cholesky_invert due to COSMA

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1303] opened 2021-01-13 17:34 UTC
Some MD benchmarks indicate that depending on the system and distribution, using COSMA as a drop-in replacement for ScaLAPACK's `p?gemm` may have a detrimental effect on the performance (2-10x slowdown). Being able to runtime-enable/disable COSMA might be useful to use the same binary (like in an HPC environment).

Results from single runs of the QS H2O-64 benchmark on Alps/Eiger for different combinations of nodes/ranks-per-node/threads-per-rank:

```
      ndsXrkXthr  w COSMA  w/o COSMA
H2O-64 001x16x001  113.325    91.972
H2O-64 001x16x008   52.169    58.794
H2O-64 001x16x016   52.282    57.014
H2O-64 001x32x001   92.991    70.400
H2O-64 001x32x004   52.922    55.827
H2O-64 001x32x008   47.206    52.074
H2O-64 001x64x001   82.751    59.122
H2O-64 002x16x001   86.097    60.065
H2O-64 002x32x001   49.011    44.661
H2O-64 002x32x004   38.814    41.799
H2O-64 002x32x008   36.725    34.418
H2O-64 002x64x001   44.567    42.155
H2O-64 002x64x002   43.750    40.968
H2O-64 004x16x001   42.407    40.835
H2O-64 004x16x008   23.166    29.085
H2O-64 004x16x016   28.860    38.558
H2O-64 004x32x004   27.440    34.376
H2O-64 004x32x008   33.463    33.509
H2O-64 004x64x001   38.561    31.303
H2O-64 004x64x004   40.259    34.583
H2O-64 008x16x001   26.896    34.986
H2O-64 008x16x016   27.898    34.209
H2O-64 008x32x001   22.859    29.652
H2O-64 008x32x004   21.519    30.548
H2O-64 008x32x008   32.602    28.152
H2O-64 008x64x001   97.097    57.198
H2O-64 008x64x002   56.865    30.906
H2O-64 008x64x004   59.107    23.895
H2O-64 016x16x001   29.727    22.195
H2O-64 016x16x008   24.580    30.904
H2O-64 016x32x001   57.219    28.038
H2O-64 016x32x008   66.675    34.022
H2O-64 016x64x001   57.809    23.472
H2O-64 016x64x002   59.376    23.472
H2O-64 016x64x004   45.507    25.930
H2O-64 032x16x001   46.417    14.291
H2O-64 032x16x008   40.335    23.079
H2O-64 032x16x016   51.210    31.355
H2O-64 032x32x001   26.210    19.150
H2O-64 032x32x004   34.538    22.598
H2O-64 032x32x008   45.671    33.595
H2O-64 032x64x001   70.165    34.154
H2O-64 032x64x002   68.457    34.545
H2O-64 032x64x004   76.184    65.280
H2O-64 064x16x001   26.098    16.464
H2O-64 064x16x008  114.806   118.204
H2O-64 064x16x016   54.157    59.624
H2O-64 064x32x001   42.855    30.415
H2O-64 064x32x004   53.473    37.060
H2O-64 064x32x008   63.877    51.211
H2O-64 064x64x001  221.895    60.353
H2O-64 064x64x002   79.736   203.070
H2O-64 064x64x004   91.319    68.089
```

**Comment by oschuett** [comment] 2021-01-13 18:48
@kabicm, what do you think?

**Comment by kabicm** [comment] 2021-01-13 19:44
I would first investigate these runs and see what the problem is.

**Comment by alazzaro** [comment] 2021-01-13 19:50
Taking another example, done by @marci73 .
From what I can see, the problem is that the function in CP2K for Cholesky just explodes on the MC partition. Check the outputs at:

/scratch/snx3000/mmi/TMP

For example the two outputs:

TiO2_oldmc18x18p2.out ==> w/ COSMA
TiO2_oldmc18x18p2_noco.out ===> w/o COSMA

The cp_fm_cholesky_invert function goes from 704.577s to 66.615s.

**Comment by alazzaro** [comment] 2021-01-13 19:51
It would be great to have an env variable that sets a threshold on the input matrix, such that we call PDGEMM (within COSMA) or COSMA given a minimum matrix size...

**Comment by oschuett** [comment] 2021-01-13 20:26
Generally, COSMA should be in the best position to make these kind of switch-over decisions. Nevertheless, a tighter integration between CP2K and COSMA might be useful. Instead of environment variables we should add a section to the regular [input](https://manual.cp2k.org/trunk/CP2K_INPUT/GLOBAL/FM.html#TYPE_OF_MATRIX_MULTIPLICATION). Furthermore, we could call COSMA upon exit to print a statistics.

**Comment by alazzaro** [comment] 2021-01-13 20:30
> Generally, COSMA should be in the best position to make these kind of switch-over decisions. Nevertheless, a tighter integration between CP2K and COSMA might be useful. Instead of environment variables we should add a section to the regular [input](https://manual.cp2k.org/trunk/CP2K_INPUT/GLOBAL/FM.html#TYPE_OF_MATRIX_MULTIPLICATION). Furthermore, we could call COSMA upon exit to print a statistics.

I think we had this discussion with COSMA people, COSMA does automatic wrapping of the PDGEMM calls. Note that the function I'm mentioning above (Cholesky) does call COSMA under the hood (it is a PDGEMM within Cray Libsci), so having a section in CP2K will not help.

**Comment by dev-zero** [comment] 2021-01-13 21:31
@kabicm the test is is CP2Ks `benchmarks/QS`, built on Alps/Eiger (COSMA built with `libsci` for BLAS/ScaLAPACK) as fallback.

The other problem with the drop-in is that it is difficult to assess whether or not a CP2K binary is actually using COSMA.

**Comment by dev-zero** [comment] 2021-01-14 07:52
> I would first investigate these runs and see what the problem is.

I used `cmake -DCOSMA_BLAS=CRAY_LIBSCI -DCOSMA_SCALAPACK=CRAY_LIBSCI ../cosma` to build COSMA.

**Comment by dev-zero** [comment] 2021-01-14 08:00
> Generally, COSMA should be in the best position to make these kind of switch-over decisions. Nevertheless, a tighter integration between CP2K and COSMA might be useful. Instead of environment variables we should add a section to the regular [input](https://manual.cp2k.org/trunk/CP2K_INPUT/GLOBAL/FM.html#TYPE_OF_MATRIX_MULTIPLICATION). Furthermore, we could call COSMA upon exit to print a statistics.

Printing statistics and the configuration (COSMA has several tuning parameters and can have a different fallback for local-only data than the main program itself) could already be a good way to get some information on whether or not `COSMA` was called at all and how.
At the moment it is impossible to determine whether an arbitrary CP2K executable is linked to COSMA (except when investigating the binary with `readelf`), which backend is used for local-only calculations, etc.

**Comment by dev-zero** [comment] 2021-01-18 15:05
And another issue with this transparent "overloading" of `p?gemm` arises when libraries called from CP2K issue `p?gemm` calls: whether or not those libraries will also use COSMA depends on the order the libraries were passed to the linker and/or whether they are shared libraries themselves and/or whether they are built with `-fvisibility=hidden` and/or the OS and/or other flags possibly passed to the linker (possibly transparently from the compiler). See the following for some analysis:

* https://holtstrom.com/michael/blog/post/437/Shared-Library-Symbol-Conflicts-(on-Linux).html
* https://www.downtowndougbrown.com/2021/01/tracking-down-a-segfault-that-suddenly-started-happening/

This sounds increasingly like no fun and near impossible to debug when not directly involved (e.g. via a user error report).
@kabicm I couldn't find any documentation wrt linker order in COSMA so far, did you look into this at some point?

**Comment by kabicm** [comment] 2021-01-20 07:39
Sorry for the late reply, I am still on holidays and will get back to this issue next week.

**Comment by oschuett** [comment] 2021-02-15 11:28
Gentle ping. Any news on this @kabicm?

**Comment by kabicm** [comment] 2021-02-23 09:32
I am sorry for such a delay, now I am back on this issue. What is the minimum example that I can run to reproduce this problem? I also think it is probably related to the cholesky function.

**Comment by oschuett** [comment] 2021-02-23 10:37
Thanks for taking a look @kabicm! The numbers [above](https://github.com/cp2k/cp2k/issues/1303#issue-785301164) were obtained using our [H2O-64.inp](https://github.com/cp2k/cp2k/blob/master/benchmarks/QS/H2O-64.inp) benchmark, which can run on a single node. If you need something smaller try [H2O-32.inp](https://github.com/cp2k/cp2k/blob/master/benchmarks/QS/H2O-32.inp).

**Comment by kabicm** [comment] 2021-02-25 11:48
Thanks @oschuett for the fast response. After having another look at the H2O-64.inp results, it seems the slowdown introduced by COSMA are mostly on suboptimal configurations: when having over- or under-subscribed cores. So it seems to me that most of these are anyway irrelevant for the user? What @alazzaro mentions however (quoting: "The cp_fm_cholesky_invert function goes from 704.577s to 66.615s.") seems more relevant, so I will focus on that now.

@alazzaro are these results also reproducible on daint? which configuration should I use?

**Comment by kabicm** [comment] 2021-02-25 12:11
@alazzaro From the input file it seems to me the input file `/scratch/snx3000/mmi/TMP/TiO2_BENCHMARK/TiO2_oldmc18x18p2.inp` was run on 18 nodes (Piz Daint mc), with 18 ranks per node and 2 threads per rank. Is this correct?

I would need the data file: `@set data /project/s965/fbrandal/data..` mentioned in the input file `/scratch/snx3000/mmi/TMP/TiO2_BENCHMARK/TiO2_oldmc18x18p2.inp`, because it's missing.

**Comment by alazzaro** [comment] 2021-02-25 12:43
> @alazzaro From the input file it seems to me the input file `/scratch/snx3000/mmi/TMP/TiO2_BENCHMARK/TiO2_oldmc18x18p2.inp` was run on 18 nodes (Piz Daint mc), with 18 ranks per node and 2 threads per rank. Is this correct?
> 
> I would need the data file: `@set data /project/s965/fbrandal/data..` mentioned in the input file `/scratch/snx3000/mmi/TMP/TiO2_BENCHMARK/TiO2_oldmc18x18p2.inp`, because it's missing.

This is a question for @marci73 ...

**Comment by marci73** [comment] 2021-02-25 13:21
Hi 

I have copied the four needed data files in /scratch/snx3000/mmi/TMP/TiO2_BENCHMARK/
Hence @set data /project/s965/fbrandal/data has to be modified accordingly
Anyway these are the usual data files in cp2k/data

Yes the run was on 18 nodes with 18 ranks and 2 threads

Best
Marcella

**Comment by kabicm** [comment] 2021-03-02 10:26
I finally managed to reproduce this problem and it should be fixable. I ran RPA-RI for 128 H2O on 128 CPU nodes, 18 ranks per node and 2 threads per rank, as @marci73 suggested. I used the latest [COSMA](https://github.com/eth-cscs/COSMA) master branch which has some performance improvements (due to the integration of [COSTA](https://github.com/eth-cscs/COSTA) into COSMA) and also the latest master branch of CP2K. 

Timings on the CPU partition (total/chokesky_decompose):
- COSMA: 471.5s / 129.9s
- MKL: 439.87s / 48.38s

The reason for the performance drop in `cholesky-`related functions is because these routines invoke a lot of small pdgemms, which are almost vector-like. In each pdgemm, COSMA is using a lot of heavy-optimizations and heuristics such as e.g. ranks relabeling, strategy-adaptation and similar, which are an overkill for small pdgemms. 

We can easily turn off these optimizations for small pdgemms, but it's not so easy to define the criteria for considering the multiplication problem  -- `small`. 

I am still experimenting with different options and will update you on the progress. Afterwards, we can make a new release of COSMA.

**Comment by alazzaro** [comment] 2021-03-02 10:32
This conclusion comes to my proposal:

> It would be great to have an env variable that sets a threshold on the input matrix, such that we call PDGEMM (within COSMA) or COSMA given a minimum matrix size...

I would leave to the user to decide what it is `small`.  Please, note also @dev-zero comment on having a way to log if COSMA is used (an env vars `COSMA_VERBOSE=1`?)

**Comment by kabicm** [comment] 2021-03-02 10:50
It would be possible to call PDGEMM in those cases, but my proposal is to still run COSMA in those cases, just without these optimizations turned on. The reason I would like to still run COSMA in those cases, is bacause it gets complicated to call  the original PDGEMM after it gets overwritten by COSMA. It's possible, but then COSMA must be built as a dynamic library, afaik.

Regarding the threshold: I am not completely sure how this threshold should look like: e.g. should the threshold refer to `m*n*k/P` or maybe some other criteria taking into account the actual shapes. 

Having COSMA logs is no problem at all! We can make it print the full statistics e.g. (m, n, k, P, throughput). Let me know if you have any kind of specific statistics/logs that you would like to be collected.

**Comment by alazzaro** [comment] 2021-03-02 11:03
OK, assuming that it depends on the shape, then I agree it gets complicated... Then, I would say, we need at least 2 vars:

1. m*n*k threshold (no need to specific P, it can be done internally)
2. m/n ratio

Of course, we can have the transpose cases...

From the tests you did, do you see any good pattern?

**Comment by oschuett** [comment] 2021-03-16 11:44
@kabicm, any news on this? We're planing a cp2k release for the end of April. Since this problem affects many of our users, do you think it could be fixed by then?

**Comment by kabicm** [comment] 2021-03-17 14:18
@oschuett @alazzaro Thanks for letting me know. We are also planning a new release of COSMA soon, that will bring some performance improvements and should fix this. Now that I know your timeframe, I will try to fit in.

**Comment by nilsholle** [comment] 2021-04-22 10:59
Are there any news regarding this issue?

**Comment by kabicm** [comment] 2021-04-22 11:09
@nilsholle This will be fixed in the next COSMA release that is coming soon. We will synchronize it with the new CP2K release.

**Comment by hfp** [comment] 2021-04-26 07:43
@kabicm Perhaps you remember my tests with common MPI/OMP-hybrid execution and rank-counts below the full core-count (before requesting at least the environment variables for more control of `pdgemm`). At that time, ScaLAPACK was faster and used less memory (I tested ScaLAPACK as included with MKL). I think COSMA made progress with default/internal parameterization/heuristics. Though, for a few ranks per node like for scale-out, COSMA was already leading (and perhaps memory consumption was in check as well).

I wonder if you think there are (significant) gaps left when comparing current performance vs ScaLAPACK (for above hybrid execution cases)? Do you think it is useful/necessary to test this on CP2K's side? ( I guess this can be also tested using the stand-alone. )

**Comment by oschuett** [comment] 2021-04-26 08:04
My understanding is that Cosma assumes `pdgemm` is always communication-bound and then trades memory for doing less communication. Hence, the performance degrades when this assumption does not hold, e.g. because the machine is either overloaded or the problem is very small and overhead-dominated. Furthermore, there might be situations where we can make better use of the memory, e.g. by storing four-center integrals.

For monitoring I'd be happy to add a suitable run to the single node benchmarks that I've setup for [CPU](https://dashboard.cp2k.org/archive/perf-openmp/index.html) and [GPU](https://dashboard.cp2k.org/archive/perf-cuda-volta/index.html) on the dashboard.

**Comment by oschuett** [comment] 2021-05-10 09:50
@kabicm, since we have the release planned for this week, I wanted to check if COSMA is still on schedule?

**Closed as completed** 2021-05-27 09:19 UTC
Labels: bug
