### ISSUE TITLE
cp2k@8.2 is stuck in the Openeuler20_aarch64 system during the test

### ISSUE THREAD

**Issue by Tom-python0121** [cp2k/cp2k#1652] opened 2021-09-28 07:44 UTC
hello,I meet a problem:cp2k@8.2 is stuck in the Openeuler20 system during the test.
### Steps to reproduce the issue

```console
command：
[root@localhost spack-src]# spack load cp2k@8.2
[root@localhost spack-src]# export OMPI_ALLOW_RUN_AS_ROOT=1
[root@localhost spack-src]# export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
[root@localhost spack-src]# make -j10 ARCH=linux-openeuler20-aarch64-gcc VERSION=popt test
……
-32/tests/QS/regtest-debug-1 (19 of 252)
Starting regression tests in /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/QS/regtest-debug-2 (20 of 252)
Starting regression tests in /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/QS/regtest-debug-3 (21 of 252)
Starting regression tests in /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/QS/regtest-cdft-diag (22 of 252)
Starting regression tests in /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/xTB/regtest-1 (23 of 252)
Starting regression tests in /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/xTB/regtest-2 (24 of 252)
Starting regression tests in /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/xTB/regtest-3 (25 of 252)
Starting regression tests in /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/xTB/regtest-4 (26 of 252)
Starting regression tests in /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/xTB/regtest-5 (27 of 252)
Starting regression tests in /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/xTB/regtest-debug (28 of 252)
Starting regression tests in /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/QS/regtest-almo-strong (29 of 252)
Starting regression tests in /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/QS/regtest-cdft-5 (30 of 252)
Starting regression tests in /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/Pimd/regtest-1 (31 of 252)
Starting regression tests in /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/Pimd/regtest-2 (32 of 252)
Starting regression tests in /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/QS/regtest-mp2-grad (33 of 252)
Starting regression tests in /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/QS/regtest-kp-2 (34 of 252)
>>> /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/UNIT/grid_unittest
    grid_unittest                                                              -     OK (   7.00 sec)
<<< /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/UNIT/grid_unittest (4 of 252) done in 7.00 sec
Starting regression tests in /home/stage/root/spack-stage-cp2k-8.2-nzeazrjq52ki3h22byplw7765mdusa76/spack-src/regtesting/linux-openeuler20-aarch64-gcc/psmp/TEST-linux-openeuler20-aarch64-gcc-psmp-2021-09-28_15-24-32/tests/QS/regtest-pao-2 (35 of 252)



```
It's stuck here. Can you help me find out why?

**Comment by oschuett** [comment] 2021-11-08 11:54
Sorry for the late reply.
It's impossible to tell from  the provided output - it could be many things.
Since this question is already pretty old I'm closing it for now.
Feel free reopen if the issue is still present.

**Closed as completed by oschuett** 2021-11-08 11:54 UTC
