### ISSUE TITLE
Bad GPU performance

### ISSUE THREAD

**Issue by antoscha** [cp2k/cp2k#73] opened 2018-11-02 11:44 UTC
Dear Developers,

I've experienced that enabling CUDA support slows down CP2K compared with pure CPU version. I tried various ways to build the executable (mostly .popt) arise from [this](https://www.cp2k.org/howto:compile_with_cuda) howto, but nothing changed.

As I know, GPU is used to accelerate matrix multiplications by DBCSR, that is set to employ a list of precomputed kernels for NVIDIA K20X, K40, K80, and P100. So I've got parameters list for my cards using [this](https://www.cp2k.org/howto:libcusmm) tutorial. And again, CPU version is much faster in, say, the official H2O-64 benchmark and in my setups as well.

I understand that is of a big request, but can GPU part of DBCSR be rewritten with the use of conventional CUDA tools or OpenACC as in [LSDalton](https://www.openacc.org/success-stories/lsdalton) instead of precomputed kernels?

Best wishes

**Comment by alazzaro** [comment] 2018-11-02 12:31
Sorry, would you mind to report your arch file, which test you are using (H2O-64 is rather small), how many ranks/nodes, your output of the test, and anything you think it will useful to understand your slowdown? 
I see two possible explanations:
1) The test is not suitable for the GPU (H2O-64 is pretty small)
2) The test is not DBCSR bound

**Comment by alazzaro** [comment] 2018-11-02 12:36
> I understand that is of a big request, but can GPU part of DBCSR be rewritten with the use of conventional CUDA tools or OpenACC as in LSDalton instead of precomputed kernels?

Could you elaborate a bit more on this statment, for instance what you want to achieve by replacing with the "conventional CUDA tools" (I assume CUBLAS) "or OpenACC"? If your problem is the autotuning GPU procedure, then we are working on a new DBCSR implementation which doesn't not require autotuning.

**Comment by alazzaro** [comment] 2018-11-02 15:51
As I suspected, the test you are using is simply too small for gaining from the GPU.
An easy way to understand the workload on the GPU is to look at this line in the output:

average stack size                                     0.0       0.0     132.6

The number of the third column should be around 10K (for the CPU should be around 1K, but the difference is negligible), in your case is pretty low and the overhead can kill the performance.

Then, let's make a comparison of the timings for the most expensive functions:

first column: CP2K function name
second column: w/ cuda
third column: w/o cuda

```
dbcsr_mm_sched_finalize            8.322     0.005
mp_alltoall_d11v                  11.291     3.836 
mp_waitany                        12.874     6.979 
acc_transpose_blocks_sync         16.938     ----------
multiply_acc_sync_right           21.496     ----------
mp_waitall_1                      35.253    16.694 
calculate_rho_elec                42.598    40.692 
integrate_v_rspace                44.506    43.998 
CP2K_Total                       252.519   160.419 
```
The last line is the total CP2K time. As you said, the nocuda is faster. Where you see "-----" these are only functions for the GPU. These sum up to ~38 seconds. Overall, cuda is always slower. 
The part in DBCSR which is related to the real computation on the GPU is:

`multiply_cannon_multrec  1.482    10.456`

Well, as you can see here the GPU does a really good job...

Note that the two main functions (calculate_rho_elec, integrate_v_rspace) are not GPU accelerated, so in any case you will limited by that.

Now, some suggestions to get better performance:
1) Of course, you can try a bigger system (H2O-256 or higher).
1) I wonder if you use PSMP for the GPU or at least a limited number of ranks (I see that you are using 24 ranks). Try with less or with a combination of ranks/threads.
2) I will drop the -D__PW_CUDA, it is useless in your case

Well, this is the GPU world, tradeoff between computation and overhead...

**Comment by hfp** [comment] 2018-11-02 17:07
What sort of CPU is it?  (Well, "GLOBAL| CPU model name :  Genuine Intel(R) CPU @ 2.00GHz" is not too specific).

**Comment by antoscha** [comment] 2018-11-02 21:16
> 1. Of course, you can try a bigger system (H2O-256 or higher).
> 2. I wonder if you use PSMP for the GPU or at least a limited number of ranks (I see that you are using 24 ranks). Try with less or with a combination of ranks/threads.
> 3. I will drop the -D__PW_CUDA, it is useless in your case

Thank you! I need some additional time to carry out tests.

**Comment by dev-zero** [comment] 2018-11-05 13:04
Closing since this is not an issue (at least, there is no evidence yet to indicate that it is). Please reopen if you think otherwise and provide more info. Also, please use our [Google Group](https://groups.google.com/group/cp2k) for future support questions.

**Closed as completed by dev-zero** 2018-11-05 13:04 UTC
Labels: invalid

**Comment by antoscha** [comment] 2018-11-05 14:18
Well, I've finished with benchmarking 256-H2O, here are results:
[73-1.tar.gz](https://github.com/cp2k/cp2k/files/2548619/73-1.tar.gz)

There is a small (3%) speedup in GPU-accelerated CP2K when using 1 thread, and a little better (9%) when using 2 threads.

As I understand, a lot of time is being consumed by dense linear algebra operations which aren't being offloading on GPU. Due to the fact that GPU computational resources much cheaper than CPU, both for ordinary customers and supercomputer centers, is there a chance for CP2K to get GPU code for dense algebra in the close future?

**Comment by hfp** [comment] 2018-11-05 20:02
Thanks for answering my question!

CP2K often relies on linear algebra for dense but relatively small matrices since the main vehicle for many of the computations is a (distributed) block-sparse matrix. Although, the blocks are dense matrices, this sort of linear algebra is not fully compute-bound. If you put non-square shapes aside and just look NxN matrix multiplications, then:

> AI(N) = 2 * N^3 / (32 * N^2) = 0.0625 * N&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(Arithmetic Intensity in FLOPS per Byte)

The arithmetic intensity (AI) for example with a 16x16 matrix only reaches 1 FLOP/Byte. Even your Haswell system yields 8 FLOPS/Byte assuming 256-bit wide vectors (AVX2) with 2 FMA ports (idealized or full utilization). That Haswell system is not compute-saturated but rather strangled by memory bandwidth, and any gain (in this case) likely comes from GPU's higher memory bandwidth (below the gain you can expect from peak FLOPS). On the other hand you have to copy the data over PCIe (and Amdahl's law somewhat kills performance). Further, the issue is emphasized with multi-node communication yet another level of "memory hierarchy" (but I guess you're only interested in single-node).

CP2K is fine on either GPU and CPU and does its best in the above case. For instance, copy over PCIe is attempted to overlap with computation. However, the smaller the AI -- the smaller the opportunity even with double-buffered/copy-swap implementation. Btw, H2O-xxx is mostly relying on 23x23-kernels which are somewhat in the upper middle-field in terms of AI.

Unfortunately, I don't have your sort of Haswell CPU but some results on Xeon E5-2699v3 (top-bin Haswell generation) comes out at roughly half your time for H2O-64 (also older version of CP2K). I think H2O-64 is kind of not representative anymore (depends on what you want to measure) for today's systems as you measure a lot of sequential/startup/overhead or communication time rather than any compute or sustained performance (at least if you look at total time to solution). Your H2O-256 (CPU) runs in ~1426s to solution, which is more than 4x behind current gen. CPUs (e.g., dual-socket Xeon SP 6148).

**Comment by antoscha** [comment] 2018-11-07 09:15
Thank you for such detailed explanation! You are doing the really great work!
