### ISSUE TITLE
`make ...` fails with `Syntax error` if `.git` is missing

### ISSUE THREAD

**Issue by mbanck** [cp2k/cp2k#1270] opened 2020-12-30 21:57 UTC
I thought that was just a problem with exported git tarballs and not the release, or was this an oversight in the 8.1 release (and/or did I grab a tarball prematurely? or is it something particular to the Debian build process?)

Anyway, I get:

```
/<<PKGBUILDDIR>>/Makefile:484: update target '/<<PKGBUILDDIR>>/obj/git-ref' due to: FORCE
echo <unknown revision> > "/<<PKGBUILDDIR>>/obj/git-ref.tmp"
/bin/sh: 1: Syntax error: redirection unexpected
make[5]: *** [/<<PKGBUILDDIR>>/Makefile:484: /<<PKGBUILDDIR>>/obj/git-ref] Error 2
make[4]: *** [/<<PKGBUILDDIR>>/Makefile:144: all] Error 2
make[3]: *** [/<<PKGBUILDDIR>>/Makefile:126: psmp] Error 2
make[2]: *** [Makefile:121: all] Error 2
[...]
cp2k-8.1# ./tools/build_utils/get_revision_number  
<unknown revision>
WARNING: ./tools/build_utils/get_revision_number failed to determine the Git commit and no REVISION file available
```
I think it's highly unfortunate that `get_revision_number` uses angle brackets for `unknown revision` and I suggest to use something else, or maybe just no brackets at all. That being said - I guess `get_revision_number` should maybe be able to figure out it is being called in a release tarball and does not need to output anything and/or this should be handled differently in this case?

**Comment by oschuett** [comment] 2020-12-30 22:10
I'm sorry, I created the tarball from the wrong branch.
I've uploaded a new tarball with sha256sum: `7f37aead120730234a60b2989d0547ae5e5498d93b1e9b5eb548c041ee8e7772`.

**Comment by mbanck** [comment] 2020-12-30 22:20
Ah ok, thanks.

I still think it'd be prudent to remove the angle brackets on master going forward, e.g. for people who hit "Dowload zip" on Github to get the latest code.

**Comment by mbanck** [comment] 2020-12-30 22:28
> I'm sorry, I created the tarball from the wrong branch.
> I've uploaded a new tarball with sha256sum: `7f37aead120730234a60b2989d0547ae5e5498d93b1e9b5eb548c041ee8e7772`.

Hrm, this one seems to have some other changes, are they all legit? (the diff is a bit weird `-` is the new tarball, `+` is the old one)

```
--- cp2k-8.1.orig/src/cp2k_info.F
+++ cp2k-8.1/src/cp2k_info.F
@@ -37,8 +37,8 @@ MODULE cp2k_info
 #if defined(__RELEASE_VERSION)
    INTEGER, PARAMETER          :: id_cp2k_version = id_release_version ! (Uncomment for release     version)
 #else
-!  INTEGER, PARAMETER          :: id_cp2k_version = id_development_version ! (Uncomment for development version)
-   INTEGER, PARAMETER          :: id_cp2k_version = 2                      ! (Uncomment for branch      version)
+   INTEGER, PARAMETER          :: id_cp2k_version = id_development_version ! (Uncomment for development version)
+!  INTEGER, PARAMETER          :: id_cp2k_version = 2                      ! (Uncomment for branch      version)
 #endif
 
 #if defined(__COMPILE_REVISION)
@@ -47,7 +47,7 @@ MODULE cp2k_info
    CHARACTER(LEN=*), PARAMETER :: compile_revision = "unknown"
 #endif
 
-   CHARACTER(LEN=*), PARAMETER :: version_nr = "8.1"
+   CHARACTER(LEN=*), PARAMETER :: version_nr = "9.0"
    CHARACTER(LEN=*), PARAMETER :: cp2k_year = "2020"
    CHARACTER(LEN=*), PARAMETER :: cp2k_version = "CP2K version "//TRIM(version_nr)
    CHARACTER(LEN=*), PARAMETER :: cp2k_home = "https://www.cp2k.org/"
--- cp2k-8.1.orig/tools/manual/index.html
+++ cp2k-8.1/tools/manual/index.html
@@ -49,7 +49,8 @@ a:link, a:visited {
 </div>
 <select id="branch_selector" style="height:25px;margin:2px;">
   <option value="trunk">Development</option>
-  <option value="cp2k-7_1-branch" selected>Version 7.1</option>
+  <option value="cp2k-8_1-branch" selected>Version 8.1</option>
+  <option value="cp2k-7_1-branch">Version 7.1</option>
   <option value="cp2k-6_1-branch">Version 6.1</option>
   <option value="cp2k-5_1-branch">Version 5.1</option>
   <option value="cp2k-4_1-branch">Version 4.1</option>
```

I guess the first one is, but the second one? Not very important, though.

**Comment by oschuett** [comment] 2020-12-30 22:36
Yes, those changes are legit. They are the diff between https://github.com/cp2k/cp2k/commit/0bfbd41a7402152da7b86a103d5d95a4184367d9 and  https://github.com/cp2k/cp2k/commit/2285224d061d2bfa6d43c73cbb105229de504238 following our [release protocol](https://www.cp2k.org/dev:release_checklist).

> for people who hit "Dowload zip" on Github to get the latest code.

Unfortunately, that's not possible as long as we're using git submodules. I'm hoping that we can drop submodules after DBCSR has moved out (#351).

I'll close this issue now. Feel free to re-open when you find other release related issues.

**Comment by dev-zero** [comment] 2021-01-04 08:45
I can still reproduce the issue when simply removing the `.git` directory in the repo and then trying to build.

So, it has nothing to do with git submodules since the GH-provided tarball/zipball reproduces this (if not the one from a release, then the one you can get for any branch or commit by using `[Code]/Download ZIP`) @oschuett

Besides, a lot of packages (all autotools-based, and any Python-package uploaded to pip for example) require a `dist` build step to build release tarballs, which could be fully automated as we have done in DBCSR. There is nothing special with having to roll a custom release tarball nor is it a special feat to not having to do it.  How we handle issue reports and that we write robust code can make a difference though.

**Comment by mbanck** [comment] 2021-01-04 10:27
I think Ole's point was that the zip-download that Github provides right now is useless as it is missing the (still) required dbcsr git submodule, so even if `get_revision_number` would not provoke the syntax error, the build would fail later on.

But that does not prevent changing `get_revision_number` now to make it more robust.

I think it's a general Github/Gitlab problem that a lot of projects (especially autotools-based ones) require special steps to prepare a release tarball. Probably a Github-Action (or Gitlab-CI) pipeline would allow to automate that.

**Comment by mbanck** [comment] 2021-12-30 15:23
For the record, I tried to test the master branch before the 9.1 release and hit this again.

As there are no prerelease tarballs, I downloaded the master zip, and added dbcsr via git clone and (inside dbcsr) fypp via git submodule.

**Comment by oschuett** [comment] 2021-12-30 15:47
Thanks for flagging @mbanck! I've opened #1846.

**Comment by mbanck** [comment] 2021-12-30 15:59
Heh, I just filed the same PR

**Comment by oschuett** [comment] 2021-12-30 16:02
Hehe, then the honors is yours :-)

**Comment by mbanck** [comment] 2021-12-30 16:04
by the way, the angle brackets are also a problem with `cp2k_manual.xml`:

```
Error on line 135 column 37 of cp2k_input.xml:
  SXXP0003: Error reported by XML parser: Attribute name "revision" associated with an
  element type "unknown" must be followed by the ' = ' character.
Transformation failed: Run-time errors were reported
```

**Comment by oschuett** [comment] 2021-12-30 16:09
So two birds with one stone. Neat!

**Closed as completed** 2021-12-30 17:36 UTC
Labels: bug
