### ISSUE TITLE
The forces doesn't print when using REFTRAJ

### ISSUE THREAD

**Issue by jingganglan** [cp2k/cp2k#1003] opened 2020-07-24 14:03 UTC
&MOTION

  &MD
    ENSEMBLE REFTRAJ
    STEPS 100
    TIMESTEP 0.5
    &REFTRAJ
      FIRST_SNAPSHOT 1
      LAST_SNAPSHOT  100
      STRIDE 1
      EVAL_ENERGY_FORCES
      TRAJ_FILE_NAME ./landmarks.xyz
    &END REFTRAJ
  &END MD
  &PRINT
    &FORCES
      &EACH
        MD 1
      &END
    &END
    &TRAJECTORY
      &EACH
        MD 1
      &END
    &END
  &END PRINT

When the reference trajectory is used to recalculate the forces along the trajectory. The forces file only print 0.000

**Comment by OndrejMarsalek** [comment] 2020-08-06 16:48
Have you tried the `EVAL_FORCES` option? It defaults to false. `EVAL_ENERGY_FORCES` is now probably a somewhat unfortunate name for the original option.

https://manual.cp2k.org/trunk/CP2K_INPUT/MOTION/MD/REFTRAJ.html#EVAL_FORCES

**Comment by oschuett** [comment] 2020-08-06 17:49
Duplicate of #894.

**Closed as completed by oschuett** 2020-08-06 17:49 UTC
