### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by picassotech** [cp2k/cp2k#2282] opened 2022-09-14 04:36 UTC
![image](https://user-images.githubusercontent.com/46565864/190060539-06b86c9b-d06c-4944-99a8-942ec1b51985.png)
I need help with this installation as there's no makefile folder in 2020-2022 version of cp2k. You need to update installation instructions for windows.

**Comment by alazzaro** [comment] 2022-09-14 08:33
duplicate of https://github.com/cp2k/cp2k/issues/2059
There is no Windows support, the wiki page is outdated... I suggest to use Ubuntu on Windows, so that you can install via Linux.

**Closed as completed** 2022-09-14 11:08 UTC
