### ISSUE TITLE
Test QS/regtest-pod/hellium-pbe-5A.inp unstable

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#1] opened 2018-10-02 11:54 UTC
Sometimes, the test QS/regtest-pod/hellium-pbe-5A.inp gives wrong results, for example on POPT version at UZH, see:

https://dashboard.cp2k.org/archive/gcc492-mkl1121-popt/rev_18530.txt

or PSMP

https://dashboard.cp2k.org/archive/gcc492-mkl1121-psmp/rev_18523.txt

Submitted by @alazzaro

**Comment by oschuett** [comment] 2018-10-02 11:56
I think it would be safe to drop this test if the problem persists.

The three hellium tests in [regtest-pod](https://github.com/cp2k/cp2k/tree/master/cp2k/tests/QS/regtest-pod) are all identical apart from the He-He separation and should go through the same sections of code. Assuming that the [shortest distance test](https://github.com/cp2k/cp2k/blob/master/cp2k/tests/QS/regtest-pod/hellium-pbe-3A.inp) is stable, I would say that nothing would be lost in terms of code coverage or tested features if only that test was kept. There's nothing immediately obvious that would explain why the test is occasionally unstable.

Submitted by @nholmber

**Comment by alazzaro** [comment] 2019-02-05 19:41
The problem is still there (see current test on dashboard). It is rare, but I would propose to drop the test as suggested by @nholmber

**Comment by alazzaro** [comment] 2019-04-09 06:58
Closing because we cannot reproduce it anymore.

**Closed as completed by alazzaro** 2019-04-09 06:58 UTC
