### ISSUE TITLE
how to install cp2k 7.1 on mac os

### ISSUE THREAD

**Issue by xvlinihao** [cp2k/cp2k#1006] opened 2020-07-25 02:36 UTC
hello, I am a newbie of cp2k, and I want to install cp2k 7.1 on my mac. I followed the instructions on https://www.cp2k.org/howto:compile_on_mac, but it didn't seem work. I met this problem:

Element of assumed-shape or pointer array as actual argument at (1) cannot correspond to actual argument at (2)
![image](https://user-images.githubusercontent.com/40994287/88447163-e4440000-ce62-11ea-9bbe-3e9134069e88.png)

I am not familiar with fortran, so I don't know how to solve it. Can someone help me resolve it. Thanks

**Comment by dev-zero** [comment] 2020-07-25 10:02
Can you please report the version of the compiler you're using? My guess it's gcc 10.x, see also #969

**Comment by dev-zero** [comment] 2020-07-28 10:01
ok, I assume that this is indeed a duplicate of #969
Please reopen if it is not!

**Closed as completed by dev-zero** 2020-07-28 10:01 UTC
