### ISSUE TITLE
Too many open files error with libxsmm 1.10

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#197] opened 2019-02-11 16:50 UTC
When I compile the current cp2k version with the Intel compiler version 18.0.5.274 (Build 20180823) using libxsmm 1.10, some (18) regression tests fail with the runtime error "too many open files" (ulimit -n 1024). The same setup gives a clean regression test with libxsmm 1.9. Did somebody observe a similar issue?

The top part of the traceback looks always like

> forrtl: severe (603): too many open files
Image              PC                Routine            Line        Source
cp2k.popt          000000000F2DB59E  for__io_return        Unknown  Unknown
cp2k.popt          000000000F2F8145  for_open              Unknown  Unknown
cp2k.popt          000000000344B96B  dbcsr_machine_int     Unknown  Unknown
cp2k.popt          000000000342C4E1  dbcsr_mm_cannon_m     Unknown  Unknown
cp2k.popt          00000000033FE2A3  dbcsr_mm_mp_dbcsr     Unknown  Unknown
cp2k.popt          000000000351538F  dbcsr_multiply_ap     Unknown  Unknown
cp2k.popt          0000000000CCD49D  cp_dbcsr_operatio     Unknown  Unknown
cp2k.popt          00000000011EA9A4  qs_mo_methods_mp_     Unknown  Unknown
...

**Comment by oschuett** [comment] 2019-02-11 19:32
Your traceback suggest that the file opening happens somewhere in `dbcsr_mm_cannon()`, which would be odd. Maybe you can trace that down? I don't think libxsmm writes any files, unless `$LIBXSMM_VERBOSE < 0`.

**Comment by hfp** [comment] 2019-02-12 08:19
I will also look into this. Looks like the reproducer is to ulimit the number of file handles.

**Comment by oschuett** [comment] 2019-02-12 09:04
The crash probably happens during the call to `m_memory()` which legitimately opens `/proc/self/statm`.

**Comment by hfp** [comment] 2019-02-12 09:17
LIBXSMM generates code in memory. One can right-away type-cast (reinterpret) such a buffer as a function-pointer and execute it. However, making a memory buffer executable such that the OS security measures are satisfied has a more complicated flow. Our mechanism works even in security-hardened environments such as SE-Linux. Anyhow, depending on the environment memory is mapped eventually based on temporary files. However, LIBXSMM does not perform explicit file I/O or is known to leak resources such as file-handles.

**Comment by mkrack** [comment] 2019-02-12 09:17
Here are some more observations from my tests:

- There is no issue with libxsmm 1.9 (clean regtest) by contrast to linking with libxsmm 1.10
- The number of failing tests correlates with the max. number of open files (ulimit -n). I still get some failing tests even setting ulimit -n to the hard limit of 4096 for my system (default is 1024). If I reduce the limit then even more tests are failing.
- I tried also -D__NO_STATM_ACCESS, since I suspected already some issue with the open file statements in m_memory, but this has only the impact that the error occurs when the restart files or another file is opened.

**Comment by hfp** [comment] 2019-02-12 09:19
@mkrack are you running the tests in a normal environment i.e., not security hardened or under hypervisor?  Can you try, LIBXSMM_SE=0 environment variable?

**Comment by mkrack** [comment] 2019-02-12 09:21
@hfp Do I need to recompile libxsmm?

**Comment by hfp** [comment] 2019-02-12 09:21
No.

**Comment by alazzaro** [comment] 2019-02-12 09:35
I remember I had this problem and it turned out it was due to dynamic linking of the library...

**Comment by mkrack** [comment] 2019-02-12 09:38
I use:
LIBS       += $(LIBXSMM_LIB)/libxsmmf.a $(LIBXSMM_LIB)/libxsmm.a

**Comment by mkrack** [comment] 2019-02-12 09:54
@hfp Great, the runtime failure disappear with LIBXSMM_SE=0 for libxsmm 1.10 and they appear again after LIBXSMM_SE=1

**Comment by hfp** [comment] 2019-02-12 09:57
@mkrack Thank you! This helps me to fix the problem in our next release. I will still try to setup a reproducer relying on ulimit.

**Comment by hfp** [comment] 2019-02-13 10:14
@mkrack Can you perhaps check the following on your system: `$ cat /sys/fs/selinux/enforce`?

**Comment by mkrack** [comment] 2019-02-13 10:16
Returns "1"

**Comment by hfp** [comment] 2019-02-13 10:33
Ok, it runs in a security-hardened environment and that's correctly detected aka `LIBXSMM_SE=1`. However, setting `LIBXSMM_SE=0` should not work then since you run with enforced SELinux. I wonder if `LIBXSMM_SE=0` in your case simply does not produce any JIT-kernel because of code-buffer allocation always fails. One could proof this with `LIBXSMM_VERBOSE=2`. This output is created at program-termination and should yield a small table of registered kernels (`stderr`).

Would you be willing to run one of the cases/tests with `LIBXSMM_VERBOSE=2` and capture `stderr`?
I mean the issue is fixed in LIBXSMM/master, but it would be good to have the complete picture.

**Comment by mkrack** [comment] 2019-02-13 12:45
The Linux-x86-64-intel-regtest-popt regression test is clean using the current libxsmm trunk version. Do you still need then the verbose error output when using 1.10?

**Comment by hfp** [comment] 2019-02-13 12:50
No thank you, I am good now. I have a test system at hand with SELinux enforced.

**Comment by dev-zero** [comment] 2019-02-13 12:56
@hfp regarding `LIBXSMM_SE`: did I understand the logic correctly in `src/libxsmm_malloc.c` that when `/sys/fs/selinux/enforce` can't be opened (for example on AppArmor-enabled kernels like the one from SUSE where SELinux is not compiled in) that it is assumed that you're running under SELinux?
What are the implications of the file workaround?

**Comment by hfp** [comment] 2019-02-13 13:06
Just to give some detail about the issue:

1. The code path draining resouces (file handles) is only entered on SELinux-enforced systems.
2. Root cause was `mkstemp`, I `unlink`'ed the file afterwards but I incorrectly assumed this closes the file handle as well (which it does not). This is fixed now.

> did I understand the logic correctly in `src/libxsmm_malloc.c` that when `/sys/fs/selinux/enforce` can't be opened [...] that it is assumed that you're running under SELinux?

No, that is not the logic. It is assumed to run under enforced SELinux **if the file exists but an error occured when reading it**. If it can be read, the actual state of SELinux is taken. In any case, `LIBXSMM_SE=1` never harms but only takes some extra effort to get an executable buffer (which is necessary for enforced SELinux).

SELinux seem to be not widely used anymore (in favour of Apparmor), and I was close to removing the support in LIBXSMM. Anyhow, I am glad we have this feature as you can see how it cranks down for instance an "ordinary" web-browser under enforced SELinux (due to JIT used without being able to get an executable buffer).

Apparmor does not require the extra effort of getting an executable buffer. Perhaps it misses this point of security but I am not sure about this.

**Comment by hfp** [comment] 2019-02-13 13:07
> What are the implications of the file workaround?

This is not a workaround, but fixing my mistake (see point No.2 above).

**Comment by dev-zero** [comment] 2019-02-13 13:11
> No, that is not the logic. It is assumed to run under enforced SELinux **if the file exists but an error occured when reading it**. If it can be read, the actual state of SELinux is taken. In any case, `LIBXSMM_SE=1` never harms but only takes some extra effort to get an executable buffer (which is necessary for enforced SELinux).

Ah, but you end up in this codepath anyway iff if the normal allocation failed, got it. Thanks!

**Comment by hfp** [comment] 2019-04-16 06:20
Let's close this issue. It is resolved in LIBXSMM/master and it will be released with v1.11.

**Closed as completed** 2019-04-16 06:20 UTC

**Comment by hfp** [comment] 2019-04-30 10:23
This bug is fixed in https://github.com/hfp/libxsmm/releases/tag/1.11. No workaround (earlier suggested envionment variable) is needed even not in SELinux environment.
